version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data1:/var/lib/postgresql/data1
  plumber:
    build: rplumber/
    restart: always
    volumes:
     - ./rplumber:/app
    ports:
     - "7001:8000"
  web:
    container_name: django
    build: maldidb/
    command: >
      gunicorn soMedia.wsgi:application --bind 0.0.0.0:8000 --workers=4
    env_file:
      - project.env
    expose:
      - 8000
    depends_on:
      - db
      - plumber
    volumes:
      - staticfiles:/home/app/web/static/
      - /home/ubuntu/r01data:/home/app/r01data/
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/static/
    depends_on:
      - web
      - db
      - plumber

volumes:
  postgres-data1:
  staticfiles:
